spring:
  application:
    name: dows-setting
  profiles:
    include: mysql,mybatis,server,rade
    active: @profileActive@

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  logging:
    level:
      root: info
