<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dows.framework</groupId>
        <artifactId>rade-parent</artifactId>
        <version>2.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>dows-setting</artifactId>
    <groupId>org.dows.cloud</groupId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <java.version>21</java.version>
        <spring-ai.version>1.0.1</spring-ai.version>
        <spring-boot.version>3.5.7</spring-boot.version>
        <fastjson2.version>2.0.58</fastjson2.version>

        <version.netty>4.2.9.Final</version.netty>

        <rade.version>1.0.251113-SNAPSHOT</rade.version>
        <disruptor.version>4.0.0</disruptor.version>
        <h2.version>2.2.224</h2.version>
        <dotenv-java.version>3.2.0</dotenv-java.version>
        <mybatis-flex.version>1.11.1</mybatis-flex.version>
    </properties>

    <modules>
        <module>setting-api</module>
        <module>setting-feign</module>
        <module>setting-app</module>
        <module>setting-boot</module>
        <module>setting-core</module>
        <module>setting-rest</module>
        <module>setting-service</module>
        <module>setting-repository</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>setting-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>setting-feign</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>setting-app</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>setting-boot</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>setting-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>setting-rest</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>setting-service</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>setting-repository</artifactId>
                <version>${project.version}</version>
            </dependency>


            <!--<dependency>
                <groupId>org.dows.cloud</groupId>
                <artifactId>rfa-api</artifactId>
                <version>1.0.0-SNAPSHOT</version>
            </dependency>-->


            <dependency>
                <groupId>org.dows.framework</groupId>
                <artifactId>rade-config</artifactId>
                <version>${rade.version}</version>
            </dependency>
            <dependency>
                <groupId>org.dows.framework</groupId>
                <artifactId>rade-crud</artifactId>
                <version>${rade.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.cdimascio</groupId>
                <artifactId>dotenv-java</artifactId>
                <version>${dotenv-java.version}</version>
            </dependency>

            <dependency>
                <groupId>com.h2database</groupId>
                <artifactId>h2</artifactId>
                <version>${h2.version}</version>
            </dependency>
            <dependency>
                <groupId>com.lmax</groupId>
                <artifactId>disruptor</artifactId>
                <version>${disruptor.version}</version>
            </dependency>


            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-core</artifactId>
                <version>5.0.4</version>
               <!-- <exclusions>
                    <exclusion>
                        <groupId>io.netty</groupId>
                        <artifactId>netty-all</artifactId>
                    </exclusion>
                </exclusions>-->
            </dependency>

            <!--<dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>${version.netty}</version>
            </dependency>-->

            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-stack-depchain</artifactId>
                <version>5.0.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!--<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>-->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

